claro_chat_bundle_chat:
    resource: "@ClarolineChatBundle/Controller/ChatController.php"
    type:     annotation
    prefix:   /
    
claro_chat_bundle_admin_chat:
    resource: "@ClarolineChatBundle/Controller/AdminChatController.php"
    type:     annotation
    prefix:   /
